name: Android CI

on:
  push:
    branches: [ Develop, master ]
  pull_request:
    branches: [ Develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Increase swapfile
      run: |
        sudo swapoff -a
        sudo fallocate -l 5G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Linter
      run: ./gradlew ktlintCheck --continue
    - name: Build with Gradle
      run: ./gradlew build
